

spring.application.name=question-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/questions
spring.datasource.username=postgres
spring.datasource.password=my1234
spring.jpa.hibernate.ddl-auto=update




